### ISSUE TITLE
Avoid race conditions for initial client connection

### ISSUE THREAD

**Issue by mnunberg** [RedisLabsModules/RLTest#11]
It appears that sometimes the client can connect before the server does, and get denied with a 'PROTECTED MODE' error. In such a case, it would be best to send a bunch of PING commands to the server until it's successful, or the server executable exits.

**Comment by MeirShpilraien** [comment]
@mnunberg is this still relevant? I did not experienced such problems.

**Comment by mnunberg** [comment]
I think we can close this.
