### ISSUE TITLE
Shorthand for common options

### ISSUE THREAD

**Issue by mnunberg** [RedisLabsModules/RLTest#6]
-x: exit on failure
-s: don't capture output

There are probably more. The shorthands are taken from Python's nosetest.

In general, the options here need to be renamed more consistently; for example `--config` is sufficient. No need for `--config-file`, and so on. Shorter options mean easier reading and less typing.

**Comment by MeirShpilraien** [comment]
@mnunberg covered?

**Comment by mnunberg** [comment]
I'd still like the `-x` or `--exit-on-failure` option. Would be convenient.

**Comment by MeirShpilraien** [comment]
So the idea is to exit on first failure right?

**Comment by mnunberg** [comment]
Yes, exit with a non-0 exit code (performing all the cleanup) rather than continuing to run. Ideally this would even be after the first failed assertion (rather than letting it continue to the end of the test function). Maybe we can even provide two different options for this?

**Comment by MeirShpilraien** [comment]
I thought just exist on the first failure (assertion or error). Do you thinks its really important to split those two?
