### ISSUE TITLE
Old RDBs are not being deleted

### ISSUE THREAD

**Issue by mnunberg** [RedisLabsModules/RLTest#9]
This means the same test cannot be run twice in the same directory

**Comment by mnunberg** [comment]
I see that this is dependent on removing the 'log dir', but this name is misleading

**Comment by MeirShpilraien** [comment]
Agree, will change the name to working dir? sounds ok?

**Comment by MeirShpilraien** [comment]
@mnunberg ?

**Comment by mnunberg** [comment]
This should be sufficient. I would also like it if it were removed automatically at test completion, but that's for later.

I'll file a new issue or just fix it later today.
